# Site settings
title: Feathers
email: hello@feathersjs.com
description: "Build better APIs, faster than ever."
baseurl: ""
url: "http://feathersjs.com"
twitter:
  author: "@ekryski"
analytics:
  provider: google
  google:
    tracking_id: UA-64904930-1

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude:
  - "node_modules"
